export const locations = [
    {
      id: 1,
      name: "New York",
      country: "United States",
      region: "North America",
      coordinates: { lat: 40.7128, lng: -74.006 },
    },
    {
      id: 2,
      name: "London",
      country: "United Kingdom",
      region: "Europe",
      coordinates: { lat: 51.5074, lng: -0.1278 },
    },
    {
      id: 3,
      name: "Tokyo",
      country: "Japan",
      region: "Asia",
      coordinates: { lat: 35.6895, lng: 139.6917 },
    },
    {
      id: 4,
      name: "Paris",
      country: "France",
      region: "Europe",
      coordinates: { lat: 48.8566, lng: 2.3522 },
    },
    {
      id: 5,
      name: "Sydney",
      country: "Australia",
      region: "Oceania",
      coordinates: { lat: -33.8688, lng: 151.2093 },
    },
    {
      id: 6,
      name: "Dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      coordinates: { lat: 25.276987, lng: 55.296249 },
    },
    {
      id: 7,
      name: "Mumbai",
      country: "India",
      region: "Asia",
      coordinates: { lat: 19.076, lng: 72.8777 },
    },
    {
      id: 8,
      name: "Cape Town",
      country: "South Africa",
      region: "Africa",
      coordinates: { lat: -33.9249, lng: 18.4241 },
    },
    {
      id: 9,
      name: "Moscow",
      country: "Russia",
      region: "Europe",
      coordinates: { lat: 55.7558, lng: 37.6173 },
    },
    {
      id: 10,
      name: "Rio de Janeiro",
      country: "Brazil",
      region: "South America",
      coordinates: { lat: -22.9068, lng: -43.1729 },
    },
    {
      id: 11,
      name: "Beijing",
      country: "China",
      region: "Asia",
      coordinates: { lat: 39.9042, lng: 116.4074 },
    },
    {
      id: 12,
      name: "Toronto",
      country: "Canada",
      region: "North America",
      coordinates: { lat: 43.65107, lng: -79.347015 },
    },
    {
      id: 13,
      name: "Berlin",
      country: "Germany",
      region: "Europe",
      coordinates: { lat: 52.52, lng: 13.405 },
    },
    {
      id: 14,
      name: "Bangkok",
      country: "Thailand",
      region: "Asia",
      coordinates: { lat: 13.7563, lng: 100.5018 },
    },
    {
      id: 15,
      name: "Los Angeles",
      country: "United States",
      region: "North America",
      coordinates: { lat: 34.0522, lng: -118.2437 },
    },
  ];
  